// ==========================================================
// services/api/src/projects/projects.constants.ts
// Canonical Seed Projects for KDI AI Office Portfolio
// ==========================================================

import type { Project } from '@kdi/types';

export const INITIAL_PORTFOLIO_PROJECTS: Project[] = [
  {
    projectId: 'prj_01_simmaci',
    slug: 'simmaci',
    name: 'SIMMACI — Academic Management & Student Statistics',
    shortDescription: 'Enterprise academic management platform and reactive statistical intelligence ecosystem for Islamic institutions.',
    description: 'SIMMACI is a mission-critical web application engineered for Islamic higher education institutions. It automates student evaluation, competition scoring resets, academic decree generation, and multi-dimensional statistical reporting with strict role-based access control.',
    category: 'Web Application',
    projectType: 'WEB_APP',
    status: 'PRODUCTION',
    publishStatus: 'PUBLISHED',
    year: '2026',
    clientType: 'Higher Education / Pesantren',
    problem: 'Manual decree tracking and fragmented student competition records caused administrative backlogs, delayed grade certifications, and lacked real-time statistical visibility across university faculties.',
    solution: 'Designed and deployed a high-throughput reactive architecture featuring automated batch reset commands, streaming Excel decree exporters, and instantaneous dean dashboard telemetry.',
    role: 'Lead Architect & Fullstack Development with Autonomous AI Engineering',
    technologies: ['Laravel', 'PHP', 'React', 'TypeScript', 'MySQL', 'TailwindCSS', 'Redis'],
    features: [
      {
        featureId: 'ft_sim_01',
        projectId: 'prj_01_simmaci',
        name: 'Decree Batch Generation & Export',
        description: 'Automated streaming export for SK Belum Mengajukan with multi-thousand student datasets without memory exhaustion.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 1,
      },
      {
        featureId: 'ft_sim_02',
        projectId: 'prj_01_simmaci',
        name: 'Reactive Student Statistics Portal',
        description: 'Interactive statistical dashboard showing faculty enrolment, academic standing distributions, and historical trends.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 2,
      },
      {
        featureId: 'ft_sim_03',
        projectId: 'prj_01_simmaci',
        name: 'Competition Scoring Reset Daemon',
        description: 'Deterministic CLI worker to safely reset competition scores across academic trimesters with transaction safety.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 3,
      },
      {
        featureId: 'ft_sim_04_internal',
        projectId: 'prj_01_simmaci',
        name: 'Internal Database Partitioning Script',
        description: 'Internal MySQL table partitioning rule for academic archiving.',
        status: 'INTERNAL',
        isPublic: false, // Internal feature - must not leak
        sortOrder: 4,
      },
    ],
    aiContribution: {
      humanContribution: 'Core business domain rules, university stakeholder interviews, regulatory compliance review, and final production authorization.',
      aiContribution: 'Autonomous code generation for export jobs, automated PHPUnit regression suites, AST refactoring of legacy controllers, and frontend TypeScript bindings.',
      engineeringAgents: ['Farhan (Software Engineer)', 'Nadia (QA Engineer)', 'Ahmad (System Architect)'],
      planningContribution: 'Automated task decomposition of 42 academic sub-modules into a dependency DAG.',
      testingContribution: '100% automated coverage for decree calculation edge cases and concurrent student score resets.',
      automationContribution: 'Continuous AST linting and safe git worktree staging.',
    },
    screenshots: [
      'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    ],
    videos: [],
    media: [
      {
        mediaId: 'med_sim_01',
        projectId: 'prj_01_simmaci',
        type: 'SCREENSHOT',
        url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
        thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=300&q=80',
        altText: 'SIMMACI Dean Statistical Overview Dashboard',
        caption: 'Dean portal rendering real-time cohort progression',
        sortOrder: 1,
        visibility: 'PUBLIC',
      },
      {
        mediaId: 'med_sim_02',
        projectId: 'prj_01_simmaci',
        type: 'ARCHITECTURE_DIAGRAM',
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
        altText: 'SIMMACI Multi-tier System Architecture',
        caption: 'Laravel REST Gateway + React 18 SPA + MySQL 8.0 cluster',
        sortOrder: 2,
        visibility: 'PUBLIC',
      },
    ],
    demoUrl: 'https://demo.simmaci.kdi-office.id',
    repositoryUrl: 'https://github.com/kdi-ai-office/simmaci-public-demo',
    isRepositoryPublic: true,
    caseStudyUrl: '/project/simmaci#case-study',
    caseStudy: {
      context: 'Islamic higher education institution serving over 15,000 active students across 6 faculties.',
      problem: 'Administrative bottlenecks in issuing graduation eligibility decrees and calculating student awards caused multi-week processing delays during graduation periods.',
      constraints: ['Zero downtime during finals period', 'Strict compliance with national higher education data models', 'PHP 8.2 & MySQL 8 environment'],
      approach: 'Introduced an asynchronous queue-backed export pipeline and automated decree state verification with transactional rollback protection.',
      architecture: 'Clean MVC separation utilizing Laravel form requests, dedicated export services, Redis job queues, and React TypeScript presentation.',
      implementation: 'Migrated legacy procedures into unified Laravel console commands and typed API endpoints with strict input validation.',
      testing: 'Executed comprehensive suite of unit and integration tests covering competition resets, export stream boundaries, and permission boundaries.',
      deployment: 'Deployed with zero-downtime rolling updates, Redis cache acceleration, and MariaDB read replicas.',
      lessonsLearned: ['Streaming exports prevent OOM crashes on large student cohorts', 'Autonomous AI agents excel at boilerplate refactoring for large legacy codebases.'],
      futureImprovements: ['Integration with national student registry API', 'Mobile app for push notifications regarding decree status.'],
    },
    architecture: {
      overview: 'Modern high-availability web architecture pairing a robust Laravel API backend with a responsive React client.',
      components: [
        {
          componentId: 'arch_sim_01',
          layer: 'FRONTEND',
          name: 'Academic Portal SPA',
          technology: 'React 18 + TypeScript + Vite',
          description: 'Client application with reactive state stores, data tables, and dynamic charting.',
        },
        {
          componentId: 'arch_sim_02',
          layer: 'BACKEND',
          name: 'Core Application Service',
          technology: 'Laravel 11 + PHP 8.2',
          description: 'REST API handling business transactions, access control, and batch processing.',
        },
        {
          componentId: 'arch_sim_03',
          layer: 'DATABASE',
          name: 'Relational Store',
          technology: 'MySQL 8.0 / MariaDB',
          description: 'ACID-compliant relational database with partitioned student history tables.',
        },
        {
          componentId: 'arch_sim_04',
          layer: 'CACHE',
          name: 'Session & Job Broker',
          technology: 'Redis 7.2',
          description: 'In-memory store for session caching and queued decree export tasks.',
        },
      ],
      dataFlow: [
        'Browser sends authenticated JWT request to Laravel Gateway',
        'Laravel middleware enforces faculty-level permission boundaries',
        'Controller queries MySQL database using optimized eager loading',
        'Heavy exports are queued in Redis and streamed back via signed download URLs',
      ],
    },
    timeline: [
      { milestoneId: 'ml_sim_01', name: 'Discovery & Requirements', phase: 'Planning', date: '2025-11-01', description: 'Academic stakeholder interviews and decree workflow mapping', completed: true },
      { milestoneId: 'ml_sim_02', name: 'Database Architecture & API', phase: 'Backend', date: '2025-12-15', description: 'Schema normalization and core REST API implementation', completed: true },
      { milestoneId: 'ml_sim_03', name: 'Reactive Dashboard Frontend', phase: 'Frontend', date: '2026-01-20', description: 'React SPA implementation with student statistics charts', completed: true },
      { milestoneId: 'ml_sim_04', name: 'Production Cutover & Verification', phase: 'Deployment', date: '2026-02-10', description: 'Live deployment and zero-downtime database migration', completed: true },
    ],
    team: [
      { memberId: 'tm_sim_01', name: 'Principal Human Architect', role: 'Solutions Architect', isAi: false, responsibilities: ['System design', 'Stakeholder alignment', 'Production authorization'] },
      { memberId: 'tm_sim_02', name: 'Farhan', role: 'Lead Software Engineer', department: 'Engineering', isAi: true, agentId: 'AGT-ENG-001', responsibilities: ['API development', 'Export optimization', 'Database migrations'] },
      { memberId: 'tm_sim_03', name: 'Nadia', role: 'QA & Security Engineer', department: 'Quality Assurance', isAi: true, agentId: 'AGT-ENG-004', responsibilities: ['Test suite automation', 'Boundary stress testing', 'Permission audit'] },
    ],
    results: [
      { metricId: 'res_sim_01', label: 'Export Processing Time', value: '94%', unit: 'Reduction', verified: true },
      { metricId: 'res_sim_02', label: 'Concurrent Users Supported', value: '1,200+', unit: 'Users', verified: true },
      { metricId: 'res_sim_03', label: 'Test Regression Coverage', value: '98.4%', unit: 'Coverage', verified: true },
    ],
    featured: true,
    visibility: 'PUBLIC',
    sortOrder: 1,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-09-25T14:30:00Z',
    internalNotes: 'Confidential client contract #KDI-EDU-2025-09. All security requirements satisfied.',
    totalCostUsd: 142.5,
    totalTokensUsed: 1845000,
    privateRepoUrl: 'git@internal.kdi.office:core/simmaci-internal.git',
    activeTaskCount: 0,
  },
  {
    projectId: 'prj_02_koneksi_santri',
    slug: 'koneksi-santri',
    name: 'Koneksi Santri — Pesantren Digital Ecosystem',
    shortDescription: 'Multi-tenant cloud platform connecting pesantren administration, digital financial ledgers, and guardian real-time updates.',
    description: 'Koneksi Santri empowers Islamic boarding institutions (Pesantren) with centralized student management, cash-free student allowances, automated tuition fee tracking, and instant WhatsApp notification gateways.',
    category: 'SaaS Platform',
    projectType: 'SAAS',
    status: 'PRODUCTION',
    publishStatus: 'PUBLISHED',
    year: '2026',
    clientType: 'Pesantren Consortium',
    problem: 'Cash-based allowance management led to loss and dispute, while guardians had no transparency into student health, memorization progress, or academic dues.',
    solution: 'Engineered an end-to-end multi-tenant SaaS platform featuring digital wallets for santri, guardian mobile access, and bank payment gateway integrations.',
    role: 'Full Lifecycle Multi-Agent Product Engineering',
    technologies: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'TailwindCSS', 'Redis'],
    features: [
      {
        featureId: 'ft_ks_01',
        projectId: 'prj_02_koneksi_santri',
        name: 'Smart Santri Digital Wallet',
        description: 'Cashless allowance management with merchant kiosk integration and guardian daily expenditure limits.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 1,
      },
      {
        featureId: 'ft_ks_02',
        projectId: 'prj_02_koneksi_santri',
        name: 'Automated Billing & Bank Gateways',
        description: 'Virtual account generation for tuition payments with automated reconciliation.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 2,
      },
      {
        featureId: 'ft_ks_03',
        projectId: 'prj_02_koneksi_santri',
        name: 'Guardian Transparency App',
        description: 'Real-time parent portal showing daily health, academic achievements, and Tahfidz progress.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 3,
      },
    ],
    aiContribution: {
      humanContribution: 'Pesantren domain consulting, financial regulatory compliance, and payment gateway contract management.',
      aiContribution: 'Autonomous development of PostgreSQL row-level security policies, payment reconciliation workers, and responsive React portals.',
      engineeringAgents: ['Farhan (Software Engineer)', 'Rian (Frontend Engineer)', 'Ahmad (System Architect)'],
      planningContribution: 'Multi-tenant architecture planning and data isolation models.',
      testingContribution: 'Automated financial ledger balance verification and idempotent transaction testing.',
      automationContribution: 'End-to-end automated deployment pipelines.',
    },
    screenshots: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    ],
    videos: [],
    media: [
      {
        mediaId: 'med_ks_01',
        projectId: 'prj_02_koneksi_santri',
        type: 'SCREENSHOT',
        url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        altText: 'Koneksi Santri Financial Ledger Dashboard',
        caption: 'Pesantren treasurer dashboard for student allowance tracking',
        sortOrder: 1,
        visibility: 'PUBLIC',
      },
    ],
    demoUrl: 'https://demo.koneksisantri.id',
    repositoryUrl: 'https://github.com/kdi-ai-office/koneksi-santri-showcase',
    isRepositoryPublic: true,
    caseStudyUrl: '/project/koneksi-santri#case-study',
    caseStudy: {
      context: 'Consortium of 12 Pesantren across East Java managing over 8,000 resident santri.',
      problem: 'Manual bookkeeping and physical cash distribution led to high administrative overhead and security vulnerabilities in student dormitories.',
      constraints: ['Multi-tenant data isolation', 'PCI-DSS compliant payment flow', 'Offline-tolerant cafeteria kiosks'],
      approach: 'Constructed a PostgreSQL-backed multi-tenant architecture with row-level security and idempotent distributed ledger entries.',
      architecture: 'Node.js Fastify API gateway, multi-tenant PostgreSQL with tenant schema isolation, Redis Pub/Sub, and React web applications.',
      implementation: 'Implemented double-entry accounting mechanics and QR-based POS kiosk clients.',
      testing: 'Simulated high-concurrency allowance disbursement with zero financial discrepancies.',
      deployment: 'Cloud container deployment on Kubernetes with automated daily backups.',
      lessonsLearned: ['Double-entry bookkeeping is mandatory for audit-proof digital wallets in educational institutions.'],
      futureImprovements: ['Biometric payment confirmation for primary school students.'],
    },
    architecture: {
      overview: 'Multi-tenant microservice platform delivering financial operations and student reporting.',
      components: [
        { componentId: 'arch_ks_01', layer: 'FRONTEND', name: 'Admin & Guardian Portal', technology: 'React + TypeScript', description: 'Responsive multi-tenant web application.' },
        { componentId: 'arch_ks_02', layer: 'BACKEND', name: 'Ledger Engine', technology: 'Node.js + Fastify', description: 'Double-entry transaction processing backend.' },
        { componentId: 'arch_ks_03', layer: 'DATABASE', name: 'Transactional DB', technology: 'PostgreSQL 16', description: 'Multi-tenant database with strict row-level security.' },
      ],
    },
    timeline: [
      { milestoneId: 'ml_ks_01', name: 'MVP Launch', phase: 'Alpha', date: '2025-10-01', description: 'Initial single-pesantren pilot testing', completed: true },
      { milestoneId: 'ml_ks_02', name: 'Multi-tenant Expansion', phase: 'Beta', date: '2026-01-15', description: 'Rolled out to 12 partner pesantren', completed: true },
    ],
    team: [
      { memberId: 'tm_ks_01', name: 'Principal Human Architect', role: 'Product Director', isAi: false, responsibilities: ['Vision', 'Bank partnerships'] },
      { memberId: 'tm_ks_02', name: 'Farhan', role: 'Backend Lead', isAi: true, agentId: 'AGT-ENG-001', responsibilities: ['Double-entry ledger engine'] },
    ],
    results: [
      { metricId: 'res_ks_01', label: 'Payment Reconciliation Time', value: '100%', unit: 'Realtime', verified: true },
      { metricId: 'res_ks_02', label: 'Pesantren Tenants Active', value: '12', unit: 'Institutions', verified: true },
    ],
    featured: true,
    visibility: 'PUBLIC',
    sortOrder: 2,
    createdAt: '2025-10-15T08:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
    internalNotes: 'Tenant encryption keys managed via KMS.',
    totalCostUsd: 89.2,
    totalTokensUsed: 1120000,
    privateRepoUrl: 'git@internal.kdi.office:saas/koneksi-santri.git',
    activeTaskCount: 2,
  },
  {
    projectId: 'prj_03_kdi_ai_office',
    slug: 'kdi-ai-office',
    name: 'KDI AI Office — Living Virtual Office & 3D Digital Twin',
    shortDescription: 'State-of-the-art 3D living digital twin and multi-agent autonomous engineering workspace.',
    description: 'KDI AI Office transforms autonomous AI engineering from opaque CLI execution into an immersive, observable 3D digital workplace. Real backend runtime events directly drive 3D agent visual states, room navigation, whiteboard meetings, and Islamic prayer sessions.',
    category: 'AI System',
    projectType: 'AI_SYSTEM',
    status: 'PRODUCTION',
    publishStatus: 'PUBLISHED',
    year: '2026',
    clientType: 'Enterprise Internal & Public Showcase',
    problem: 'AI software agents historically operate as disjointed, headless background scripts with zero spatial context, making system status and collaborative progress difficult to observe.',
    solution: 'Built an authoritative backend-driven 3D digital twin using PlayCanvas React, WebSocket streaming, deterministic waypoint navigation, and Neo4j GraphRAG memory.',
    role: 'Core Architecture, 3D Engineering & Autonomous Multi-Agent Runtime',
    technologies: ['PlayCanvas', 'React', 'TypeScript', 'NestJS', 'PostgreSQL', 'Neo4j', 'Redis', 'TailwindCSS'],
    features: [
      {
        featureId: 'ft_kdi_01',
        projectId: 'prj_03_kdi_ai_office',
        name: '3D Living Virtual Office',
        description: '14 canonical modular rooms in WebGL 2.0 with dynamic avatars representing digital employees.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 1,
      },
      {
        featureId: 'ft_kdi_02',
        projectId: 'prj_03_kdi_ai_office',
        name: 'Authoritative Backend-to-3D Sync',
        description: 'Zero fake animation. State updates stream via WebSocket with versioned snapshot reconciliation.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 2,
      },
      {
        featureId: 'ft_kdi_03',
        projectId: 'prj_03_kdi_ai_office',
        name: 'Neo4j GraphRAG & Institutional Memory',
        description: 'Knowledge graph storing 10 entity types and 12 relation types for deep semantic reasoning.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 3,
      },
      {
        featureId: 'ft_kdi_04',
        projectId: 'prj_03_kdi_ai_office',
        name: 'Islamic Salah & Wellness Lifecycle',
        description: 'Automated prayer session management with non-destructive task context preservation.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 4,
      },
    ],
    aiContribution: {
      humanContribution: 'System vision, architectural gates, Islamic workplace ethics design, and zero-trust security policies.',
      aiContribution: 'Self-authored modular 3D scene architecture, deterministic BFS waypoint routing, and complete unit/integration test suites.',
      engineeringAgents: ['Farhan (Software Engineer)', 'Rian (Frontend Engineer)', 'Ahmad (System Architect)', 'Nadia (QA Engineer)', 'Maya (Product Manager)'],
      planningContribution: 'Decomposed 7 complex phases into verifiable milestone deliverables.',
      testingContribution: '120 monorepo tests verifying WebSocket reconnects, version sequencing, and memory bounding.',
      automationContribution: 'Autonomous code editing and continuous monorepo compilation.',
    },
    screenshots: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    ],
    videos: [],
    media: [
      {
        mediaId: 'med_kdi_01',
        projectId: 'prj_03_kdi_ai_office',
        type: 'SCREENSHOT',
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
        altText: 'KDI AI Office Living 3D Digital Twin Viewport',
        caption: 'Real-time PlayCanvas 3D scene reflecting agent positions and server rack health',
        sortOrder: 1,
        visibility: 'PUBLIC',
      },
    ],
    demoUrl: 'https://office.kdi-office.id',
    repositoryUrl: 'https://github.com/kdi-ai-office/living-virtual-office',
    isRepositoryPublic: true,
    caseStudyUrl: '/project/kdi-ai-office#case-study',
    caseStudy: {
      context: 'Internal digital twin for KDI AI software engineering operations.',
      problem: 'Coordinating multiple autonomous agents requires transparent observability without overloading operators with raw console logs.',
      constraints: ['Integrated GPU compatibility (60 FPS on basic hardware)', 'Zero fake state simulation', 'Strict public/private data isolation'],
      approach: 'Adopted PlayCanvas React for declarative 3D composition driven strictly by backend WebSocket envelopes.',
      architecture: 'NestJS authoritative state server, Redis Pub/Sub, PlayCanvas React WebGL client, and Neo4j graph storage.',
      implementation: 'Built a 24-waypoint deterministic router and 11-clip blended animation state machine.',
      testing: 'Validated with 20 end-to-end digital twin verification tests with zero simulated passes.',
      deployment: 'Hostinger frontend bundle served via CDN with secure WSS gateway to office server.',
      lessonsLearned: ['PlayCanvas provides superior frame performance on integrated Intel GPUs compared to heavy alternatives.'],
      futureImprovements: ['Cinematic camera director cuts', 'Multi-tenant office branch layout support.'],
    },
    architecture: {
      overview: 'Hybrid 3D and React application driven by a centralized NestJS authoritative state engine.',
      components: [
        { componentId: 'arch_kdi_01', layer: 'FRONTEND', name: '3D WebGL Scene & React HUD', technology: 'PlayCanvas React + Vite', description: 'Declarative 3D digital twin rendering 14 modular rooms.' },
        { componentId: 'arch_kdi_02', layer: 'BACKEND', name: 'Authoritative Office Engine', technology: 'NestJS + Node.js 22', description: 'Real-time WebSocket event broadcaster and snapshot provider.' },
        { componentId: 'arch_kdi_03', layer: 'DATABASE', name: 'Relational & Vector Cache', technology: 'PostgreSQL 16 + Redis 7', description: 'Operational task storage and high-speed telemetry broker.' },
        { componentId: 'arch_kdi_04', layer: 'AI', name: 'Knowledge Graph & Memory', technology: 'Neo4j 5.20+ & GraphRAG', description: 'Multi-hop associative agent memory and decision auditing.' },
      ],
    },
    timeline: [
      { milestoneId: 'ml_kdi_01', name: 'Phase 1: Foundation & PlayCanvas Spike', phase: 'Architecture', date: '2026-08-01', description: 'WebGL 2.0 spike and avatar rendering', completed: true },
      { milestoneId: 'ml_kdi_02', name: 'Phase 3: Runtime & Orchestration', phase: 'Engine', date: '2026-08-20', description: '15-state task machine and worker pool', completed: true },
      { milestoneId: 'ml_kdi_03', name: 'Phase 5: Neo4j GraphRAG', phase: 'AI', date: '2026-09-10', description: 'Associative memory and 3-hop graph queries', completed: true },
      { milestoneId: 'ml_kdi_04', name: 'Phase 6: Living 3D Digital Twin', phase: '3D', date: '2026-09-30', description: '14 modular rooms, deterministic navigation, and Salah cycle', completed: true },
    ],
    team: [
      { memberId: 'tm_kdi_01', name: 'Principal Human Architect', role: 'Chief Architect', isAi: false, responsibilities: ['Platform governance', 'Security boundaries'] },
      { memberId: 'tm_kdi_02', name: 'Ahmad', role: 'Principal System Architect', isAi: true, agentId: 'AGT-ARCH-001', responsibilities: ['Architecture verification'] },
      { memberId: 'tm_kdi_03', name: 'Farhan', role: 'Fullstack Engineer', isAi: true, agentId: 'AGT-ENG-001', responsibilities: ['API & WebSocket gateway'] },
    ],
    results: [
      { metricId: 'res_kdi_01', label: 'Frame Rendering Performance', value: '<0.1ms', unit: 'Update Time', verified: true },
      { metricId: 'res_kdi_02', label: 'Automated Test Pass Rate', value: '100%', unit: '120/120 Tests', verified: true },
      { metricId: 'res_kdi_03', label: 'Modular 3D Rooms Implemented', value: '14', unit: 'Rooms', verified: true },
    ],
    featured: true,
    visibility: 'PUBLIC',
    sortOrder: 3,
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-09-30T08:30:00Z',
    internalNotes: 'Showcase system for KDI AI capabilities. Public presentation ready.',
    totalCostUsd: 310.4,
    totalTokensUsed: 4200000,
    privateRepoUrl: 'git@internal.kdi.office:platform/living-office.git',
    activeTaskCount: 3,
  },
  {
    projectId: 'prj_04_quran_tracker',
    slug: 'quran-memorization-tracker',
    name: 'Quran Memorization & Tahfidz Tracker',
    shortDescription: 'Mobile and web tracker for Ayah-by-Ayah memorization tracking with AI-assisted retention verification.',
    description: 'An Islamic spiritual and educational utility helping students and teachers track Mutabaah Yaumiyyah, Murajaah schedules, and Ayah retention milestones with historical progress graphs.',
    category: 'Mobile & Web App',
    projectType: 'MOBILE_APP',
    status: 'PRODUCTION',
    publishStatus: 'PUBLISHED',
    year: '2026',
    clientType: 'Islamic Foundation',
    problem: 'Traditional paper mutabaah logbooks were easily lost, lacked objective retention tracking, and prevented parents from seeing memorization milestones in real-time.',
    solution: 'Constructed an offline-first mobile app with cloud synchronization that tracks Surah retention levels, spaced repetition reminders, and teacher verification signatures.',
    role: 'System Architecture & Fullstack Engineering',
    technologies: ['Flutter', 'Dart', 'FastAPI', 'Python', 'PostgreSQL'],
    features: [
      {
        featureId: 'ft_qt_01',
        projectId: 'prj_04_quran_tracker',
        name: 'Spaced Repetition Murajaah Schedule',
        description: 'Algorithmic review reminder based on forgetting curve analysis for previously memorized Juz.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 1,
      },
      {
        featureId: 'ft_qt_02',
        projectId: 'prj_04_quran_tracker',
        name: 'Teacher Oral Exam Log',
        description: 'Digital signature and grading rubric for Sanad-aligned teacher testing.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 2,
      },
    ],
    aiContribution: {
      humanContribution: 'Tajweed rules verification, Ustadz consultation, and Islamic educational methodology.',
      aiContribution: 'Flutter UI component generation, FastAPI backend endpoints, and PostgreSQL schema indexing.',
      engineeringAgents: ['Farhan (Software Engineer)', 'Nadia (QA Engineer)'],
    },
    screenshots: [
      'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=1200&q=80',
    ],
    videos: [],
    media: [
      {
        mediaId: 'med_qt_01',
        projectId: 'prj_04_quran_tracker',
        type: 'SCREENSHOT',
        url: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=1200&q=80',
        altText: 'Quran Memorization Progress View',
        caption: 'Visual Surah map highlighting memorized, review-needed, and upcoming portions',
        sortOrder: 1,
        visibility: 'PUBLIC',
      },
    ],
    demoUrl: 'https://tahfidz.kdi-office.id',
    repositoryUrl: 'https://github.com/kdi-ai-office/tahfidz-tracker-client',
    isRepositoryPublic: true,
    caseStudyUrl: '/project/quran-memorization-tracker#case-study',
    caseStudy: {
      context: 'Islamic school network serving 3,200 Tahfidz students.',
      problem: 'High student dropout from retention burnout due to lack of structured spaced-repetition Murajaah.',
      constraints: ['Must function completely offline in low-connectivity rural pesantren', 'Arabic script rendering precision'],
      approach: 'Offline-first SQLite local store paired with background synchronization to FastAPI.',
      architecture: 'Flutter mobile client, FastAPI REST gateway, PostgreSQL master.',
      implementation: 'Engineered an Arabic typography renderer and spaced-repetition algorithm.',
      testing: 'Offline sync conflict resolution verified through automated property-based tests.',
      deployment: 'Published on Google Play and progressive web app.',
      lessonsLearned: ['Offline-first sync requires deterministic vector clocks to avoid overwriting memorization grades.'],
      futureImprovements: ['Audio waveform analysis for Tajweed pronunciation coaching.'],
    },
    architecture: {
      overview: 'Offline-first mobile application synchronizing with high-speed Python backend.',
      components: [
        { componentId: 'arch_qt_01', layer: 'FRONTEND', name: 'Mobile Application', technology: 'Flutter + Dart', description: 'Cross-platform offline-first mobile client.' },
        { componentId: 'arch_qt_02', layer: 'BACKEND', name: 'Sync Gateway', technology: 'FastAPI + Python 3.11', description: 'High-speed asynchronous sync endpoint.' },
      ],
    },
    timeline: [
      { milestoneId: 'ml_qt_01', name: 'Release 1.0', phase: 'Production', date: '2026-03-01', description: 'Launched across 4 pesantren schools', completed: true },
    ],
    team: [
      { memberId: 'tm_qt_01', name: 'Principal Human Architect', role: 'Project Sponsor', isAi: false, responsibilities: ['Islamic compliance'] },
      { memberId: 'tm_qt_02', name: 'Farhan', role: 'Software Engineer', isAi: true, agentId: 'AGT-ENG-001', responsibilities: ['Flutter & FastAPI sync engine'] },
    ],
    results: [
      { metricId: 'res_qt_01', label: 'Average Juz Retention Rate', value: '+38%', unit: 'Improvement', verified: true },
      { metricId: 'res_qt_02', label: 'Active Daily Mutabaah Logs', value: '2,800+', unit: 'Logs/day', verified: true },
    ],
    featured: false,
    visibility: 'PUBLIC',
    sortOrder: 4,
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-03-15T09:00:00Z',
    internalNotes: 'Open access community project sponsored by Islamic foundation.',
    totalCostUsd: 45.0,
    totalTokensUsed: 620000,
    privateRepoUrl: 'git@internal.kdi.office:community/tahfidz-internal.git',
    activeTaskCount: 0,
  },
  {
    projectId: 'prj_05_graph_intelligence',
    slug: 'graph-rag-memory',
    name: 'Neo4j GraphRAG & Institutional Memory Engine',
    shortDescription: 'High-dimensional semantic knowledge graph and associative memory engine for multi-agent reasoning.',
    description: 'Autonomous multi-agent intelligence system powered by Neo4j graph storage and vector embeddings, enabling bounded multi-hop traversals across codebases, architectural decisions, and agent execution histories.',
    category: 'AI Research',
    projectType: 'RESEARCH',
    status: 'PRODUCTION',
    publishStatus: 'PUBLISHED',
    year: '2026',
    clientType: 'AI Engineering Core',
    problem: 'Standard vector RAG suffers from catastrophic context loss across deep dependency chains, making architectural impact analysis and multi-turn decision tracking unreliable.',
    solution: 'Designed a hybrid GraphRAG associative memory storing 10 node types and 12 relationship types, providing bounded 3-hop traversal and semantic edge discovery.',
    role: 'Research & Core Graph Systems Engineering',
    technologies: ['Neo4j', 'Cypher', 'Ollama', 'Python', 'NestJS', 'TypeScript'],
    features: [
      {
        featureId: 'ft_gr_01',
        projectId: 'prj_05_graph_intelligence',
        name: 'Bounded 3-Hop Entity Expansion',
        description: 'Constrained multi-hop Cypher queries preventing memory explosion while maintaining deep relational context.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 1,
      },
      {
        featureId: 'ft_gr_02',
        projectId: 'prj_05_graph_intelligence',
        name: 'Institutional Decision Graph',
        description: 'Auditable ADR and task dependency graph linking code commits to architectural rationale.',
        status: 'PRODUCTION',
        isPublic: true,
        sortOrder: 2,
      },
    ],
    aiContribution: {
      humanContribution: 'Ontology design, relationship schema governance, and safety boundary constraints.',
      aiContribution: 'Cypher query optimization, benchmark test harness authoring, and schema verification scripts.',
      engineeringAgents: ['Ahmad (System Architect)', 'Farhan (Software Engineer)'],
    },
    screenshots: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    ],
    videos: [],
    media: [
      {
        mediaId: 'med_gr_01',
        projectId: 'prj_05_graph_intelligence',
        type: 'ARCHITECTURE_DIAGRAM',
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
        altText: 'Neo4j Graph Topology Schema Diagram',
        caption: '10 node entity types linked by 12 typed relations',
        sortOrder: 1,
        visibility: 'PUBLIC',
      },
    ],
    demoUrl: 'https://graph.kdi-office.id',
    repositoryUrl: undefined, // Private repository - must show safe public notice
    isRepositoryPublic: false,
    caseStudyUrl: '/project/graph-rag-memory#case-study',
    caseStudy: {
      context: 'Core reasoning backbone for KDI multi-agent engineering workflows.',
      problem: 'Vector-only embeddings cannot resolve transitive relations such as "which tasks broke the tests for this architecture decision?".',
      constraints: ['Max 3-hop traversal latency under 50ms', 'Zero credential exposure'],
      approach: 'Constructed an associative graph model utilizing Neo4j 5.20+ with typed relationship indexing.',
      architecture: 'Neo4j Enterprise cluster, Ollama local embedding models, and NestJS Graph Module.',
      implementation: 'Authored Cypher templates with query parameterization and strict limit guards.',
      testing: 'Verified over 500 edge traversals with 0 circular loop traps and memory overhead < 128MB.',
      deployment: 'Dockerized microservice orchestrated via internal office server.',
      lessonsLearned: ['Graph limits are essential to avoid query runaway during complex agent memory lookups.'],
      futureImprovements: ['Temporal graph replay for step-by-step decision forensics.'],
    },
    architecture: {
      overview: 'Graph-native associative memory architecture paired with local vector embeddings.',
      components: [
        { componentId: 'arch_gr_01', layer: 'AI', name: 'Graph Database Engine', technology: 'Neo4j 5.20+', description: 'Property graph database with vector indexing capabilities.' },
        { componentId: 'arch_gr_02', layer: 'AI', name: 'Embedding Provider', technology: 'Ollama + nomic-embed-text', description: 'Local zero-cost embedding generation.' },
      ],
    },
    timeline: [
      { milestoneId: 'ml_gr_01', name: 'Ontology Formalization', phase: 'Design', date: '2026-08-15', description: 'Defined 10 node types and 12 relation schemas', completed: true },
      { milestoneId: 'ml_gr_02', name: 'Phase 5 GraphRAG Verification', phase: 'Integration', date: '2026-09-10', description: 'Passed all 14 integration test suites', completed: true },
    ],
    team: [
      { memberId: 'tm_gr_01', name: 'Ahmad', role: 'Principal Architect', isAi: true, agentId: 'AGT-ARCH-001', responsibilities: ['Ontology design', 'Cypher optimization'] },
    ],
    results: [
      { metricId: 'res_gr_01', label: 'Average Traversal Latency', value: '18.4ms', unit: 'Query Time', verified: true },
      { metricId: 'res_gr_02', label: 'Relationship Traversal Depth', value: '3-Hop', unit: 'Bounded Limit', verified: true },
    ],
    featured: false,
    visibility: 'PUBLIC',
    sortOrder: 5,
    createdAt: '2026-08-10T08:00:00Z',
    updatedAt: '2026-09-15T12:00:00Z',
    internalNotes: 'Proprietary graph schema. Private algorithms must not be published.',
    totalCostUsd: 195.0,
    totalTokensUsed: 2900000,
    privateRepoUrl: 'git@internal.kdi.office:ai/graph-rag-memory.git',
    activeTaskCount: 1,
  },
  // ==========================================================
  // Private / Internal / Draft Test Fixtures
  // (MUST NEVER BE RETURNED BY PUBLIC API)
  // ==========================================================
  {
    projectId: 'prj_06_internal_billing',
    slug: 'internal-billing-automation',
    name: 'Internal Billing & Cloud Cost Ledger',
    shortDescription: 'Private financial cost accounting worker for internal server infrastructure.',
    description: 'Confidential internal system tracking GPU token burn rates, cloud VPS hosting fees, and salary allocations.',
    category: 'Internal System',
    projectType: 'INTERNAL_SYSTEM',
    status: 'DEVELOPMENT',
    publishStatus: 'DRAFT',
    year: '2026',
    clientType: 'KDI Internal Operations',
    problem: 'Internal cost tracking required manual invoice matching.',
    solution: 'Automated cost ledger parsing cloud API bills.',
    role: 'Internal DevOps',
    technologies: ['NestJS', 'PostgreSQL', 'Docker'],
    features: [],
    aiContribution: { humanContribution: 'Audit', aiContribution: 'Billing scripts', engineeringAgents: ['Farhan'] },
    screenshots: [],
    videos: [],
    media: [],
    isRepositoryPublic: false,
    timeline: [],
    team: [],
    results: [],
    featured: false,
    visibility: 'INTERNAL', // Must be filtered out from public API
    sortOrder: 99,
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-02-05T08:00:00Z',
    internalNotes: 'Strictly confidential internal ledger. Contains employee salary grades.',
    totalCostUsd: 55.0,
    totalTokensUsed: 400000,
    privateRepoUrl: 'git@internal.kdi.office:ops/internal-billing.git',
  },
  {
    projectId: 'prj_07_confidential_audit',
    slug: 'bank-security-audit',
    name: 'Confidential Banking Security Audit Engine',
    shortDescription: 'Proprietary penetration testing and vulnerability analysis suite.',
    description: 'Classified security testing harness for financial institution perimeter defense.',
    category: 'Security Testing',
    projectType: 'EXPERIMENTAL',
    status: 'PROTOTYPE',
    publishStatus: 'REVIEW',
    year: '2026',
    clientType: 'Private Bank',
    problem: 'Classified',
    solution: 'Classified',
    role: 'Security Audit',
    technologies: ['Python', 'Rust'],
    features: [],
    aiContribution: { humanContribution: 'Penetration testing', aiContribution: 'Exploit modeling', engineeringAgents: ['Nadia'] },
    screenshots: [],
    videos: [],
    media: [],
    isRepositoryPublic: false,
    timeline: [],
    team: [],
    results: [],
    featured: false,
    visibility: 'CONFIDENTIAL', // Must be filtered out from public API
    sortOrder: 100,
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-02T08:00:00Z',
    internalNotes: 'Strict NDA. Never disclose client identity or technical vulnerability findings.',
    totalCostUsd: 820.0,
    totalTokensUsed: 9800000,
    privateRepoUrl: 'git@internal.kdi.office:sec/bank-audit.git',
  },
];
