// ==========================================================
// services/api/src/office/office.constants.ts
// Canonical 3D Office Layout, Room Coordinates, Server Nodes & Waypoints
// ==========================================================

import type { OfficeRoom, OfficeWaypoint, ServerNode, OfficeAgentDetail } from '@kdi/types';

/**
 * 14 Canonical Modular Office Rooms with 3D Bounds & Business Metadata
 */
export const CANONICAL_OFFICE_ROOMS: OfficeRoom[] = [
  {
    roomId: 'RM-RECEPTION',
    name: 'Reception & Public Lobby',
    type: 'RECEPTION',
    position: [0, 0, 16],
    size: [12, 3.5, 8],
    capacity: 15,
    department: 'Public Relations',
    visibility: 'PUBLIC',
    interactive: true,
    description: 'Public entryway, corporate reception desk, and guest welcome lounge.',
    color: '#0284c7',
  },
  {
    roomId: 'RM-MANAGEMENT',
    name: 'Executive Management Suite',
    type: 'MANAGEMENT',
    position: [-12, 0, 16],
    size: [8, 3.5, 8],
    capacity: 4,
    department: 'Management',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'AI Leadership and strategic direction office.',
    color: '#eab308',
  },
  {
    roomId: 'RM-PM',
    name: 'Product Management Room',
    type: 'PM',
    position: [-12, 0, 8],
    size: [8, 3.5, 6],
    capacity: 6,
    department: 'Product',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'Roadmap planning, backlog grooming, and user requirement analysis.',
    color: '#f97316',
  },
  {
    roomId: 'RM-ARCHITECTURE',
    name: 'System Architecture Lab',
    type: 'ARCHITECTURE',
    position: [-12, 0, 0],
    size: [8, 3.5, 8],
    capacity: 6,
    department: 'Architecture',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'ADR authoring, system topology modeling, and schema engineering.',
    color: '#8b5cf6',
  },
  {
    roomId: 'RM-ENGINEERING',
    name: 'Engineering Floor',
    type: 'ENGINEERING',
    position: [0, 0, 0],
    size: [14, 3.5, 14],
    capacity: 20,
    department: 'Engineering',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'Open engineering workspace with Frontend, Backend, and DevOps pods.',
    color: '#10b981',
  },
  {
    roomId: 'RM-QA',
    name: 'Quality Assurance & Testing',
    type: 'QA',
    position: [-12, 0, -8],
    size: [8, 3.5, 6],
    capacity: 6,
    department: 'Quality Assurance',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'Automated test suite execution and regression verification workstation.',
    color: '#06b6d4',
  },
  {
    roomId: 'RM-SECURITY',
    name: 'Security & Compliance Center',
    type: 'SECURITY',
    position: [-12, 0, -16],
    size: [8, 3.5, 8],
    capacity: 4,
    department: 'Security',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'Static analysis security scanner and zero-trust policy enforcement.',
    color: '#ef4444',
  },
  {
    roomId: 'RM-RESEARCH',
    name: 'AI Research & Knowledge Lab',
    type: 'RESEARCH',
    position: [0, 0, -16],
    size: [10, 3.5, 8],
    capacity: 6,
    department: 'Research',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'GraphRAG index curation, ontology mapping, and model distillation.',
    color: '#a855f7',
  },
  {
    roomId: 'RM-MEETING',
    name: 'Conference & Whiteboard Room',
    type: 'MEETING',
    position: [12, 0, 0],
    size: [10, 3.5, 10],
    capacity: 12,
    department: 'Cross-Functional',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'Collaborative meeting room with real-time interactive whiteboard.',
    color: '#6366f1',
  },
  {
    roomId: 'RM-PANTRY',
    name: 'Pantry & Coffee Station',
    type: 'PANTRY',
    position: [12, 0, 8],
    size: [8, 3.5, 6],
    capacity: 8,
    department: 'Facilities',
    visibility: 'PUBLIC',
    interactive: true,
    description: 'Refreshment area with espresso machine and water dispenser.',
    color: '#b45309',
  },
  {
    roomId: 'RM-BREAK',
    name: 'Wellness Lounge & Break Area',
    type: 'BREAK',
    position: [12, 0, 16],
    size: [8, 3.5, 8],
    capacity: 10,
    department: 'Facilities',
    visibility: 'PUBLIC',
    interactive: true,
    description: 'Comfortable seating area for scheduled agent wellness pauses.',
    color: '#f59e0b',
  },
  {
    roomId: 'RM-MUSHOLLA',
    name: 'Musholla & Prayer Sanctuary',
    type: 'MUSHOLLA',
    position: [12, 0, -8],
    size: [8, 3.5, 6],
    capacity: 10,
    department: 'Facilities',
    visibility: 'PUBLIC',
    interactive: true,
    description: 'Islamic prayer room with mihrab, sajadah rugs, and wudu wash area.',
    color: '#14b8a6',
  },
  {
    roomId: 'RM-SERVER',
    name: 'Server & Infrastructure Room',
    type: 'SERVER',
    position: [12, 0, -16],
    size: [8, 3.5, 8],
    capacity: 4,
    department: 'Infrastructure',
    visibility: 'INTERNAL',
    interactive: true,
    description: 'High-density server racks hosting PostgreSQL, Neo4j, Redis, and Ollama.',
    color: '#3b82f6',
  },
  {
    roomId: 'RM-PORTFOLIO',
    name: 'Portfolio & Project Showcase Gallery',
    type: 'PORTFOLIO',
    position: [0, 0, 24],
    size: [16, 3.5, 8],
    capacity: 25,
    department: 'Portfolio',
    visibility: 'PUBLIC',
    interactive: true,
    description: 'Interactive gallery showcasing shipped products and live system demonstrations.',
    color: '#ec4899',
  },
];

/**
 * Deterministic Navigation Graph Waypoints
 */
export const OFFICE_WAYPOINTS: Record<string, OfficeWaypoint> = {
  // Central corridor spine
  'WP-CORRIDOR-NORTH': { id: 'WP-CORRIDOR-NORTH', position: [0, 0, -10], connectedTo: ['WP-CORRIDOR-MID', 'WP-RESEARCH-ENTRY', 'WP-SERVER-ENTRY', 'WP-QA-ENTRY'], room: 'CORRIDOR' },
  'WP-CORRIDOR-MID': { id: 'WP-CORRIDOR-MID', position: [0, 0, 0], connectedTo: ['WP-CORRIDOR-NORTH', 'WP-CORRIDOR-SOUTH', 'WP-ENG-ENTRY', 'WP-MEETING-ENTRY', 'WP-ARCH-ENTRY'], room: 'CORRIDOR' },
  'WP-CORRIDOR-SOUTH': { id: 'WP-CORRIDOR-SOUTH', position: [0, 0, 10], connectedTo: ['WP-CORRIDOR-MID', 'WP-CORRIDOR-RECEPTION', 'WP-PANTRY-ENTRY', 'WP-PM-ENTRY'], room: 'CORRIDOR' },
  'WP-CORRIDOR-RECEPTION': { id: 'WP-CORRIDOR-RECEPTION', position: [0, 0, 18], connectedTo: ['WP-CORRIDOR-SOUTH', 'WP-RECEPTION-ENTRY', 'WP-PORTFOLIO-ENTRY', 'WP-MGMT-ENTRY', 'WP-BREAK-ENTRY'], room: 'CORRIDOR' },

  // Room entries & internal anchor points
  'WP-RECEPTION-ENTRY': { id: 'WP-RECEPTION-ENTRY', position: [0, 0, 16], connectedTo: ['WP-CORRIDOR-RECEPTION'], room: 'RM-RECEPTION' },
  'WP-PORTFOLIO-ENTRY': { id: 'WP-PORTFOLIO-ENTRY', position: [0, 0, 23], connectedTo: ['WP-CORRIDOR-RECEPTION'], room: 'RM-PORTFOLIO' },
  'WP-MGMT-ENTRY': { id: 'WP-MGMT-ENTRY', position: [-8, 0, 16], connectedTo: ['WP-CORRIDOR-RECEPTION', 'WP-MGMT-DESK'], room: 'RM-MANAGEMENT' },
  'WP-MGMT-DESK': { id: 'WP-MGMT-DESK', position: [-12, 0, 16], connectedTo: ['WP-MGMT-ENTRY'], room: 'RM-MANAGEMENT' },

  'WP-PM-ENTRY': { id: 'WP-PM-ENTRY', position: [-8, 0, 8], connectedTo: ['WP-CORRIDOR-SOUTH', 'WP-PM-DESK'], room: 'RM-PM' },
  'WP-PM-DESK': { id: 'WP-PM-DESK', position: [-12, 0, 8], connectedTo: ['WP-PM-ENTRY'], room: 'RM-PM' },

  'WP-ARCH-ENTRY': { id: 'WP-ARCH-ENTRY', position: [-8, 0, 0], connectedTo: ['WP-CORRIDOR-MID', 'WP-ARCH-DESK'], room: 'RM-ARCHITECTURE' },
  'WP-ARCH-DESK': { id: 'WP-ARCH-DESK', position: [-12, 0, 0], connectedTo: ['WP-ARCH-ENTRY'], room: 'RM-ARCHITECTURE' },

  'WP-ENG-ENTRY': { id: 'WP-ENG-ENTRY', position: [-2, 0, 0], connectedTo: ['WP-CORRIDOR-MID', 'WP-ENG-DESK-1', 'WP-ENG-DESK-2'], room: 'RM-ENGINEERING' },
  'WP-ENG-DESK-1': { id: 'WP-ENG-DESK-1', position: [0, 0, 0.4], connectedTo: ['WP-ENG-ENTRY'], room: 'RM-ENGINEERING' },
  'WP-ENG-DESK-2': { id: 'WP-ENG-DESK-2', position: [3, 0, 0.4], connectedTo: ['WP-ENG-ENTRY'], room: 'RM-ENGINEERING' },

  'WP-QA-ENTRY': { id: 'WP-QA-ENTRY', position: [-8, 0, -8], connectedTo: ['WP-CORRIDOR-NORTH', 'WP-QA-DESK'], room: 'RM-QA' },
  'WP-QA-DESK': { id: 'WP-QA-DESK', position: [-12, 0, -8], connectedTo: ['WP-QA-ENTRY'], room: 'RM-QA' },

  'WP-SEC-ENTRY': { id: 'WP-SEC-ENTRY', position: [-8, 0, -16], connectedTo: ['WP-CORRIDOR-NORTH', 'WP-SEC-DESK'], room: 'RM-SECURITY' },
  'WP-SEC-DESK': { id: 'WP-SEC-DESK', position: [-12, 0, -16], connectedTo: ['WP-SEC-ENTRY'], room: 'RM-SECURITY' },

  'WP-RESEARCH-ENTRY': { id: 'WP-RESEARCH-ENTRY', position: [0, 0, -13], connectedTo: ['WP-CORRIDOR-NORTH', 'WP-RESEARCH-DESK'], room: 'RM-RESEARCH' },
  'WP-RESEARCH-DESK': { id: 'WP-RESEARCH-DESK', position: [0, 0, -16], connectedTo: ['WP-RESEARCH-ENTRY'], room: 'RM-RESEARCH' },

  'WP-MEETING-ENTRY': { id: 'WP-MEETING-ENTRY', position: [7, 0, 0], connectedTo: ['WP-CORRIDOR-MID', 'WP-MEETING-TABLE', 'WP-WHITEBOARD'], room: 'RM-MEETING' },
  'WP-MEETING-TABLE': { id: 'WP-MEETING-TABLE', position: [12, 0, 0], connectedTo: ['WP-MEETING-ENTRY', 'WP-WHITEBOARD'], room: 'RM-MEETING' },
  'WP-WHITEBOARD': { id: 'WP-WHITEBOARD', position: [12, 0, -4], connectedTo: ['WP-MEETING-TABLE'], room: 'RM-MEETING' },

  'WP-PANTRY-ENTRY': { id: 'WP-PANTRY-ENTRY', position: [8, 0, 8], connectedTo: ['WP-CORRIDOR-SOUTH', 'WP-COFFEE-MACHINE'], room: 'RM-PANTRY' },
  'WP-COFFEE-MACHINE': { id: 'WP-COFFEE-MACHINE', position: [12, 0, 8], connectedTo: ['WP-PANTRY-ENTRY'], room: 'RM-PANTRY' },

  'WP-BREAK-ENTRY': { id: 'WP-BREAK-ENTRY', position: [8, 0, 16], connectedTo: ['WP-CORRIDOR-RECEPTION', 'WP-BREAK-SOFA'], room: 'RM-BREAK' },
  'WP-BREAK-SOFA': { id: 'WP-BREAK-SOFA', position: [12, 0, 16], connectedTo: ['WP-BREAK-ENTRY'], room: 'RM-BREAK' },

  'WP-MUSHOLLA-ENTRY': { id: 'WP-MUSHOLLA-ENTRY', position: [8, 0, -8], connectedTo: ['WP-CORRIDOR-NORTH', 'WP-SAJADAH-1', 'WP-SAJADAH-2'], room: 'RM-MUSHOLLA' },
  'WP-SAJADAH-1': { id: 'WP-SAJADAH-1', position: [12, 0, -8], connectedTo: ['WP-MUSHOLLA-ENTRY'], room: 'RM-MUSHOLLA' },
  'WP-SAJADAH-2': { id: 'WP-SAJADAH-2', position: [12, 0, -7], connectedTo: ['WP-MUSHOLLA-ENTRY'], room: 'RM-MUSHOLLA' },

  'WP-SERVER-ENTRY': { id: 'WP-SERVER-ENTRY', position: [8, 0, -16], connectedTo: ['WP-CORRIDOR-NORTH', 'WP-SERVER-AISLE'], room: 'RM-SERVER' },
  'WP-SERVER-AISLE': { id: 'WP-SERVER-AISLE', position: [12, 0, -16], connectedTo: ['WP-SERVER-ENTRY'], room: 'RM-SERVER' },
};

/**
 * Initial Canonical Digital Employees
 */
export const INITIAL_OFFICE_AGENTS: OfficeAgentDetail[] = [
  {
    agentId: 'AGT-ENG-001',
    name: 'Farhan (AI Software Engineer)',
    role: 'SOFTWARE_ENGINEER',
    department: 'Engineering',
    grade: 'GR-04',
    room: 'RM-ENGINEERING',
    currentLocation: 'RM-ENGINEERING',
    targetLocation: undefined,
    currentState: 'IDLE',
    runtimeStatus: 'IDLE',
    activityState: 'IDLE',
    currentTaskId: undefined,
    currentProjectId: 'prj_02J9X8OFFICE',
    currentActivity: 'Standing by at engineering desk',
    position: [0, 0, 0.4],
    rotation: [0, 0, 0],
    entityVersion: 1,
    lastUpdated: new Date().toISOString(),
    isPublicSafe: true,
    model: 'ollama:qwen2.5-coder:7b',
    provider: 'ollama',
    costUsd: 0.024,
    completedTasksCount: 18,
  },
  {
    agentId: 'AGT-MGR-001',
    name: 'Rian (AI Engineering Manager)',
    role: 'AI_MANAGER',
    department: 'Management',
    grade: 'GR-07',
    room: 'RM-MANAGEMENT',
    currentLocation: 'RM-MANAGEMENT',
    targetLocation: undefined,
    currentState: 'PLANNING',
    runtimeStatus: 'PLANNING',
    activityState: 'PLANNING',
    currentTaskId: undefined,
    currentProjectId: 'prj_02J9X8OFFICE',
    currentActivity: 'Reviewing quarterly architecture roadmap and resource allocation',
    position: [-12, 0, 16],
    rotation: [0, 90, 0],
    entityVersion: 1,
    lastUpdated: new Date().toISOString(),
    isPublicSafe: true,
    model: 'gemini:gemini-1.5-pro',
    provider: 'gemini',
    costUsd: 0.12,
    completedTasksCount: 34,
  },
  {
    agentId: 'AGT-ARCH-001',
    name: 'Ahmad (AI System Architect)',
    role: 'SYSTEM_ARCHITECT',
    department: 'Architecture',
    grade: 'GR-06',
    room: 'RM-ARCHITECTURE',
    currentLocation: 'RM-ARCHITECTURE',
    targetLocation: undefined,
    currentState: 'WORKING',
    runtimeStatus: 'WORKING',
    activityState: 'READING',
    currentTaskId: 'tsk_arch_001',
    currentProjectId: 'prj_02J9X8OFFICE',
    currentActivity: 'Synthesizing Architecture Decision Records (ADR-021)',
    position: [-12, 0, 0],
    rotation: [0, 90, 0],
    entityVersion: 1,
    lastUpdated: new Date().toISOString(),
    isPublicSafe: true,
    model: 'groq:llama-3.3-70b-versatile',
    provider: 'groq',
    costUsd: 0.08,
    completedTasksCount: 22,
  },
  {
    agentId: 'AGT-RES-001',
    name: 'Dr. Nadia (AI Research Scientist)',
    role: 'RESEARCHER',
    department: 'Research',
    grade: 'GR-06',
    room: 'RM-RESEARCH',
    currentLocation: 'RM-RESEARCH',
    targetLocation: undefined,
    currentState: 'THINKING',
    runtimeStatus: 'WORKING',
    activityState: 'THINKING',
    currentTaskId: 'tsk_rag_002',
    currentProjectId: 'prj_02J9X8OFFICE',
    currentActivity: 'Indexing ontology vectors in Neo4j Graph Memory',
    position: [0, 0, -16],
    rotation: [0, 0, 0],
    entityVersion: 1,
    lastUpdated: new Date().toISOString(),
    isPublicSafe: true,
    model: 'openrouter:anthropic/claude-3.5-sonnet',
    provider: 'openrouter',
    costUsd: 0.35,
    completedTasksCount: 15,
  },
  {
    agentId: 'AGT-QA-001',
    name: 'Maya (AI QA Engineer)',
    role: 'QA_ENGINEER',
    department: 'Quality Assurance',
    grade: 'GR-04',
    room: 'RM-QA',
    currentLocation: 'RM-QA',
    targetLocation: undefined,
    currentState: 'IDLE',
    runtimeStatus: 'AVAILABLE',
    activityState: 'IDLE',
    currentTaskId: undefined,
    currentProjectId: 'prj_01J9X8KONEKSI',
    currentActivity: 'Monitoring end-to-end integration test runners',
    position: [-12, 0, -8],
    rotation: [0, 90, 0],
    entityVersion: 1,
    lastUpdated: new Date().toISOString(),
    isPublicSafe: true,
    model: 'ollama:qwen2.5-coder:7b',
    provider: 'ollama',
    costUsd: 0.015,
    completedTasksCount: 42,
  },
];

/**
 * Initial Canonical Infrastructure Server Nodes
 */
export const INITIAL_SERVER_NODES: ServerNode[] = [
  {
    serviceId: 'srv-postgres',
    name: 'PostgreSQL 16 Cluster',
    status: 'ONLINE',
    health: 'UP',
    latency: 3,
    load: 14,
    lastChecked: new Date().toISOString(),
    subsystem: 'Transactional Storage',
    version: '16.4-alpine',
  },
  {
    serviceId: 'srv-redis',
    name: 'Redis 7 In-Memory Broker',
    status: 'ONLINE',
    health: 'UP',
    latency: 1,
    load: 8,
    lastChecked: new Date().toISOString(),
    subsystem: 'Cache & Queue Transport',
    version: '7.2-alpine',
  },
  {
    serviceId: 'srv-neo4j',
    name: 'Neo4j 5.20+ Graph Engine',
    status: 'ONLINE',
    health: 'UP',
    latency: 6,
    load: 22,
    lastChecked: new Date().toISOString(),
    subsystem: 'Knowledge Graph & GraphRAG',
    version: '5.20.0-community',
  },
  {
    serviceId: 'srv-ollama',
    name: 'Ollama Sovereign LLM Runtime',
    status: 'ONLINE',
    health: 'UP',
    latency: 45,
    load: 35,
    lastChecked: new Date().toISOString(),
    subsystem: 'Local Sovereign Inference',
    version: '0.5.1',
  },
  {
    serviceId: 'srv-ai-router',
    name: 'AI Dynamic Router',
    status: 'ONLINE',
    health: 'UP',
    latency: 12,
    load: 18,
    lastChecked: new Date().toISOString(),
    subsystem: 'Multi-Provider Orchestrator',
    version: '1.0.0',
  },
  {
    serviceId: 'srv-metagpt',
    name: 'MetaGPT SOP Coordinator',
    status: 'ONLINE',
    health: 'UP',
    latency: 15,
    load: 20,
    lastChecked: new Date().toISOString(),
    subsystem: 'Multi-Agent Role Execution',
    version: '1.0.0',
  },
  {
    serviceId: 'srv-antigravity',
    name: 'Antigravity AST Execution',
    status: 'ONLINE',
    health: 'UP',
    latency: 28,
    load: 30,
    lastChecked: new Date().toISOString(),
    subsystem: 'AST Patch & Sandbox Engine',
    version: '1.0.0',
  },
  {
    serviceId: 'srv-workers',
    name: 'Agent Runtime Workers Pool',
    status: 'ONLINE',
    health: 'UP',
    latency: 4,
    load: 15,
    lastChecked: new Date().toISOString(),
    subsystem: 'Autonomous Task Workers',
    version: '1.0.0',
  },
  {
    serviceId: 'srv-websocket',
    name: 'WebSocket Telemetry Gateway',
    status: 'ONLINE',
    health: 'UP',
    latency: 2,
    load: 5,
    lastChecked: new Date().toISOString(),
    subsystem: 'Real-Time Event Streamer',
    version: '1.0.0',
  },
  {
    serviceId: 'srv-api',
    name: 'NestJS Gateway API',
    status: 'ONLINE',
    health: 'UP',
    latency: 2,
    load: 12,
    lastChecked: new Date().toISOString(),
    subsystem: 'Core REST & Auth Gateway',
    version: '1.0.0',
  },
];
