// ==========================================================
// services/api/src/workforce/workforce.constants.ts
// Canonical Real-World Salary Sources, Market Roles & Benchmarks
// ==========================================================

import type {
  SalaryBenchmarkSource,
  MarketRole,
  SalaryBenchmark,
  WorkloadProfile,
  VirtualEmployee,
} from '@kdi/types';

export const INITIAL_SALARY_SOURCES: SalaryBenchmarkSource[] = [
  {
    sourceId: 'src_glints_2026',
    name: 'Glints Tech Talent & Salary Report 2026',
    provider: 'Glints Indonesia',
    url: 'https://employers.glints.id/salary-report',
    country: 'Indonesia',
    region: 'National / Java Regional',
    dataType: 'Tech Salary Survey & Hiring Benchmarks',
    publicationDate: '2026-01-15',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    methodology: 'Aggregated cross-sectional salary survey of 1,200+ Indonesian tech companies and verified job placement records.',
    reliabilityTier: 'TIER_B',
    notes: 'Recognized industry standard for Indonesian software, design, and digital operations roles.',
  },
  {
    sourceId: 'src_page_2026',
    name: 'Michael Page Indonesia Salary Benchmark Guide 2026',
    provider: 'Michael Page International',
    url: 'https://www.michaelpage.co.id/salary-guide',
    country: 'Indonesia',
    region: 'National Indonesia',
    dataType: 'Executive & Technical Recruitment Benchmark',
    publicationDate: '2026-02-01',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    methodology: 'Derived from proprietary placement database and quantitative analysis of corporate salary bands.',
    reliabilityTier: 'TIER_B',
    notes: 'High reliability for engineering, architectural, and digital leadership positions.',
  },
  {
    sourceId: 'src_jobstreet_2026',
    name: 'Jobstreet by SEEK Indonesia Salary Insights 2026',
    provider: 'Jobstreet / SEEK',
    url: 'https://www.jobstreet.co.id/career-advice/salary-guide',
    country: 'Indonesia',
    region: 'Central Java & National Remote',
    dataType: 'Job Board Salary Disclosures & Employer Listings',
    publicationDate: '2026-03-10',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    methodology: 'Statistical median extraction from active employer job postings disclosing base monthly compensation.',
    reliabilityTier: 'TIER_C',
    notes: 'Strong coverage for regional roles in Central Java (Semarang, Purwokerto, Cilacap).',
  },
  {
    sourceId: 'src_bps_jateng_2026',
    name: 'BPS Provinsi Jawa Tengah — Indikator Upah Tenaga Kerja Sektor Informasi & Komunikasi',
    provider: 'Badan Pusat Statistik (BPS)',
    url: 'https://jateng.bps.go.id/indicator/6/keadaan-ketenagakerjaan.html',
    country: 'Indonesia',
    region: 'Jawa Tengah (Central Java)',
    dataType: 'Official Government Labor Statistics & Survey',
    publicationDate: '2026-02-28',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    methodology: 'Survei Angkatan Kerja Nasional (Sakernas) analyzing average net monthly wages for technical and media labor.',
    reliabilityTier: 'TIER_A',
    notes: 'Official state baseline for Central Java regional labor compensation.',
  },
];

export const INITIAL_MARKET_ROLES: MarketRole[] = [
  {
    marketRoleId: 'mkt_web_admin',
    canonicalTitle: 'Web Administrator',
    category: 'Information Technology',
    description: 'Manages website availability, domain routing, server maintenance, SSL certificates, and core portal infrastructure.',
    alternateTitles: ['Website Administrator', 'Webmaster', 'Web Operations Specialist', 'Site Reliability Operator'],
    typicalSkills: ['DNS Management', 'Apache/Nginx', 'SSL/TLS', 'HTML/CSS', 'Linux Shell', 'Backup Recovery'],
    typicalTools: ['cPanel', 'Cloudflare', 'Bash', 'Git', 'Uptime Kuma', 'Google Search Console'],
    normalizedKdiLevel: 'MID',
    standardFteHoursPerWeek: 40,
  },
  {
    marketRoleId: 'mkt_wp_specialist',
    canonicalTitle: 'WordPress / CMS Specialist',
    category: 'Content & Web Engineering',
    description: 'Designs, customizes, updates, and hardens WordPress CMS platforms, themes, hooks, plugins, and caching pipelines.',
    alternateTitles: ['WordPress Developer', 'CMS Administrator', 'WordPress Webmaster', 'PHP CMS Specialist'],
    typicalSkills: ['PHP', 'WordPress Theme Hooks', 'Plugin Customization', 'Database Optimization', 'Security Hardening'],
    typicalTools: ['WordPress', 'Elementor', 'WooCommerce', 'WP-CLI', 'MySQL Workbench', 'LiteSpeed Cache'],
    normalizedKdiLevel: 'MID',
    standardFteHoursPerWeek: 40,
  },
  {
    marketRoleId: 'mkt_graphic_designer',
    canonicalTitle: 'Graphic Designer',
    category: 'Design & Creative',
    description: 'Creates brand identities, social media visual assets, publication layouts, banners, vector illustrations, and print collaterals.',
    alternateTitles: ['Visual Designer', 'Digital Creative Designer', 'Brand Designer', 'Publication Layout Designer'],
    typicalSkills: ['Vector Illustration', 'Typography', 'Color Theory', 'Layout Design', 'Print Preparation', 'Photo Manipulation'],
    typicalTools: ['Adobe Photoshop', 'Adobe Illustrator', 'Figma', 'CorelDRAW', 'Canva Pro'],
    normalizedKdiLevel: 'MID',
    standardFteHoursPerWeek: 40,
  },
  {
    marketRoleId: 'mkt_social_media',
    canonicalTitle: 'Social Media Specialist',
    category: 'Marketing & Communications',
    description: 'Plans, schedules, publishes, and analyzes content across corporate and institutional social media channels.',
    alternateTitles: ['Social Media Officer', 'Social Media Manager', 'Digital Community Specialist', 'Content Distribution Officer'],
    typicalSkills: ['Content Calendar Planning', 'Copywriting', 'Hashtag Optimization', 'Audience Engagement', 'Analytics Reporting'],
    typicalTools: ['Meta Business Suite', 'Instagram Creator Studio', 'Hootsuite', 'TikTok Analytics', 'Buffer'],
    normalizedKdiLevel: 'MID',
    standardFteHoursPerWeek: 40,
  },
  {
    marketRoleId: 'mkt_content_spec',
    canonicalTitle: 'Content Publishing Specialist',
    category: 'Communications & Editorial',
    description: 'Drafts, edits, formats, and publishes formal organizational decrees, academic news articles, press releases, and documentation.',
    alternateTitles: ['Content Specialist', 'Web Content Writer', 'Documentation Specialist', 'Editorial Assistant'],
    typicalSkills: ['Copywriting', 'Proofreading', 'SEO Writing', 'Editorial Guidelines', 'Decree Formatting'],
    typicalTools: ['Google Docs', 'WordPress Editor', 'Grammarly', 'Yoast SEO', 'Markdown'],
    normalizedKdiLevel: 'MID',
    standardFteHoursPerWeek: 40,
  },
  {
    marketRoleId: 'mkt_it_support',
    canonicalTitle: 'IT Support Specialist',
    category: 'Information Technology',
    description: 'Diagnoses and resolves local office workstation issues, network connectivity, LAN routing, printer configurations, and hardware maintenance.',
    alternateTitles: ['IT Helpdesk Technician', 'Technical Support Officer', 'Desktop Support Engineer', 'LAN Administrator'],
    typicalSkills: ['Hardware Diagnostics', 'LAN/WLAN Setup', 'OS Troubleshooting', 'Printer Networking', 'Cable Crimping'],
    typicalTools: ['Mikrotik Winbox', 'AnyDesk', 'Wireshark', 'Command Prompt', 'Windows Device Manager'],
    normalizedKdiLevel: 'MID',
    standardFteHoursPerWeek: 40,
  },
  {
    marketRoleId: 'mkt_fullstack_eng',
    canonicalTitle: 'Fullstack Software Engineer',
    category: 'Software Engineering',
    description: 'Develops client-facing SPAs, server-side APIs, database schemas, and integration pipelines with automated testing.',
    alternateTitles: ['Software Developer', 'Fullstack Developer', 'Web Application Engineer'],
    typicalSkills: ['TypeScript', 'React', 'Node.js', 'NestJS', 'Laravel', 'PostgreSQL', 'Docker'],
    typicalTools: ['VS Code', 'Git', 'Postman', 'Docker', 'Vite'],
    normalizedKdiLevel: 'SENIOR',
    standardFteHoursPerWeek: 40,
  },
  {
    marketRoleId: 'mkt_sys_architect',
    canonicalTitle: 'Systems Architect',
    category: 'Architecture & Leadership',
    description: 'Defines system topology, data flow constraints, security boundaries, graph knowledge models, and deployment infrastructure.',
    alternateTitles: ['Principal Architect', 'Solutions Architect', 'Enterprise Architect'],
    typicalSkills: ['Distributed Systems', 'Graph Databases', 'Microservices', 'Threat Modeling', 'Cloud Topology'],
    typicalTools: ['Neo4j', 'Redis', 'Docker Compose', 'Mermaid.js', 'Linux'],
    normalizedKdiLevel: 'PRINCIPAL',
    standardFteHoursPerWeek: 40,
  },
  {
    marketRoleId: 'mkt_qa_engineer',
    canonicalTitle: 'QA & Security Engineer',
    category: 'Quality & Security',
    description: 'Designs automated end-to-end regression suites, security penetration tests, and validation gates.',
    alternateTitles: ['Software QA Engineer', 'Test Automation Engineer', 'Security Analyst'],
    typicalSkills: ['Automated Testing', 'Regression Suites', 'OWASP Top 10', 'Boundary Testing', 'Performance Profiling'],
    typicalTools: ['Node Test Runner', 'Jest', 'Playwright', 'OWASP ZAP'],
    normalizedKdiLevel: 'SENIOR',
    standardFteHoursPerWeek: 40,
  },
];

export const INITIAL_SALARY_BENCHMARKS: SalaryBenchmark[] = [
  {
    benchmarkId: 'bmk_web_admin_jateng',
    marketRoleId: 'mkt_web_admin',
    marketRoleTitle: 'Web Administrator',
    location: 'Central Java (Cilacap / Purwokerto / Banyumas)',
    country: 'Indonesia',
    region: 'Jawa Tengah',
    currency: 'IDR',
    salaryMin: 4200000,
    salaryMedian: 5500000,
    salaryMax: 7000000,
    experienceLevel: 'MID',
    employmentType: 'FULL_TIME',
    sourceId: 'src_jobstreet_2026',
    sourceName: 'Jobstreet by SEEK Indonesia Salary Insights 2026',
    sourceUrl: 'https://www.jobstreet.co.id/career-advice/salary-guide',
    sourceTier: 'TIER_C',
    publicationDate: '2026-03-10',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    isCurrent: true,
    isStale: false,
    confidence: 'HIGH',
    notes: 'Derived from Central Java regional IT employer disclosures.',
    version: 1,
  },
  {
    benchmarkId: 'bmk_wp_spec_jateng',
    marketRoleId: 'mkt_wp_specialist',
    marketRoleTitle: 'WordPress / CMS Specialist',
    location: 'Central Java (Cilacap / Purwokerto)',
    country: 'Indonesia',
    region: 'Jawa Tengah',
    currency: 'IDR',
    salaryMin: 4000000,
    salaryMedian: 5000000,
    salaryMax: 6500000,
    experienceLevel: 'MID',
    employmentType: 'FULL_TIME',
    sourceId: 'src_glints_2026',
    sourceName: 'Glints Tech Talent & Salary Report 2026',
    sourceUrl: 'https://employers.glints.id/salary-report',
    sourceTier: 'TIER_B',
    publicationDate: '2026-01-15',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    isCurrent: true,
    isStale: false,
    confidence: 'HIGH',
    notes: 'Verified median for PHP/WordPress customized application maintenance.',
    version: 1,
  },
  {
    benchmarkId: 'bmk_graphic_designer_jateng',
    marketRoleId: 'mkt_graphic_designer',
    marketRoleTitle: 'Graphic Designer',
    location: 'Central Java (Cilacap / Purwokerto)',
    country: 'Indonesia',
    region: 'Jawa Tengah',
    currency: 'IDR',
    salaryMin: 3800000,
    salaryMedian: 4800000,
    salaryMax: 6500000,
    experienceLevel: 'MID',
    employmentType: 'FULL_TIME',
    sourceId: 'src_bps_jateng_2026',
    sourceName: 'BPS Provinsi Jawa Tengah — Indikator Upah Tenaga Kerja',
    sourceUrl: 'https://jateng.bps.go.id/indicator/6/keadaan-ketenagakerjaan.html',
    sourceTier: 'TIER_A',
    publicationDate: '2026-02-28',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    isCurrent: true,
    isStale: false,
    confidence: 'HIGH',
    notes: 'Statistical median for creative, digital asset, and branding labor in Central Java.',
    version: 1,
  },
  {
    benchmarkId: 'bmk_social_media_jateng',
    marketRoleId: 'mkt_social_media',
    marketRoleTitle: 'Social Media Specialist',
    location: 'Central Java (Cilacap / Purwokerto)',
    country: 'Indonesia',
    region: 'Jawa Tengah',
    currency: 'IDR',
    salaryMin: 3500000,
    salaryMedian: 4500000,
    salaryMax: 6000000,
    experienceLevel: 'MID',
    employmentType: 'FULL_TIME',
    sourceId: 'src_glints_2026',
    sourceName: 'Glints Tech Talent & Salary Report 2026',
    sourceUrl: 'https://employers.glints.id/salary-report',
    sourceTier: 'TIER_B',
    publicationDate: '2026-01-15',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    isCurrent: true,
    isStale: false,
    confidence: 'HIGH',
    notes: 'Covers social media strategy, graphic scheduling, and audience community engagement.',
    version: 1,
  },
  {
    benchmarkId: 'bmk_content_spec_jateng',
    marketRoleId: 'mkt_content_spec',
    marketRoleTitle: 'Content Publishing Specialist',
    location: 'Central Java (Cilacap / Purwokerto)',
    country: 'Indonesia',
    region: 'Jawa Tengah',
    currency: 'IDR',
    salaryMin: 3500000,
    salaryMedian: 4200000,
    salaryMax: 5500000,
    experienceLevel: 'MID',
    employmentType: 'FULL_TIME',
    sourceId: 'src_jobstreet_2026',
    sourceName: 'Jobstreet by SEEK Indonesia Salary Insights 2026',
    sourceUrl: 'https://www.jobstreet.co.id/career-advice/salary-guide',
    sourceTier: 'TIER_C',
    publicationDate: '2026-03-10',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    isCurrent: true,
    isStale: false,
    confidence: 'MEDIUM',
    notes: 'Editorial news writing, academic formatting, and portal publication.',
    version: 1,
  },
  {
    benchmarkId: 'bmk_it_support_jateng',
    marketRoleId: 'mkt_it_support',
    marketRoleTitle: 'IT Support Specialist',
    location: 'Central Java (Cilacap / Purwokerto)',
    country: 'Indonesia',
    region: 'Jawa Tengah',
    currency: 'IDR',
    salaryMin: 4000000,
    salaryMedian: 5000000,
    salaryMax: 6800000,
    experienceLevel: 'MID',
    employmentType: 'FULL_TIME',
    sourceId: 'src_jobstreet_2026',
    sourceName: 'Jobstreet by SEEK Indonesia Salary Insights 2026',
    sourceUrl: 'https://www.jobstreet.co.id/career-advice/salary-guide',
    sourceTier: 'TIER_C',
    publicationDate: '2026-03-10',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    isCurrent: true,
    isStale: false,
    confidence: 'HIGH',
    notes: 'Local hardware, networking, printer troubleshooting, and desktop support.',
    version: 1,
  },
  {
    benchmarkId: 'bmk_fullstack_remote',
    marketRoleId: 'mkt_fullstack_eng',
    marketRoleTitle: 'Fullstack Software Engineer',
    location: 'National Remote Indonesia',
    country: 'Indonesia',
    currency: 'IDR',
    salaryMin: 8000000,
    salaryMedian: 12500000,
    salaryMax: 18000000,
    experienceLevel: 'SENIOR',
    employmentType: 'REMOTE',
    sourceId: 'src_glints_2026',
    sourceName: 'Glints Tech Talent & Salary Report 2026',
    sourceUrl: 'https://employers.glints.id/salary-report',
    sourceTier: 'TIER_B',
    publicationDate: '2026-01-15',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    isCurrent: true,
    isStale: false,
    confidence: 'HIGH',
    notes: 'Fullstack JavaScript/PHP/Python remote engineering across Indonesian tech firms.',
    version: 1,
  },
  {
    benchmarkId: 'bmk_architect_remote',
    marketRoleId: 'mkt_sys_architect',
    marketRoleTitle: 'Systems Architect',
    location: 'National Remote Indonesia',
    country: 'Indonesia',
    currency: 'IDR',
    salaryMin: 16000000,
    salaryMedian: 24000000,
    salaryMax: 35000000,
    experienceLevel: 'PRINCIPAL',
    employmentType: 'REMOTE',
    sourceId: 'src_page_2026',
    sourceName: 'Michael Page Indonesia Salary Benchmark Guide 2026',
    sourceUrl: 'https://www.michaelpage.co.id/salary-guide',
    sourceTier: 'TIER_B',
    publicationDate: '2026-02-01',
    retrievalDate: '2026-09-30',
    effectivePeriod: '2026',
    isCurrent: true,
    isStale: false,
    confidence: 'HIGH',
    notes: 'Principal system architect guiding distributed multi-agent systems and infrastructure.',
    version: 1,
  },
];

/**
 * Real-world human workload test fixture demonstrating the Workload Mirror:
 * ONE Human Operator handling 6 distinct job responsibilities concurrently.
 */
export const CANONICAL_WORKLOAD_PROFILE: WorkloadProfile = {
  profileId: 'prf_human_operator_01',
  personIdentifier: 'EMP-OPERATOR-01',
  title: 'Lead Systems & Digital Media Specialist',
  department: 'Information Technology & Media Communications',
  location: 'Cilacap / Purwokerto, Jawa Tengah',
  actualCompensation: {
    baseSalary: 3800000,
    allowances: 700000,
    bonuses: 0,
    other: 0,
    totalMonthly: 4500000,
    currency: 'IDR',
  },
  responsibilities: [
    {
      responsibilityId: 'resp_web_admin',
      title: 'Website Administration & DNS Operations',
      description: 'Manages uptime, domain routing, cPanel configs, and server availability for institutional websites.',
      frequency: 'DAILY',
      estimatedHoursPerWeek: 16,
      skills: ['DNS Management', 'cPanel', 'SSL/TLS', 'Linux Shell'],
      tools: ['Cloudflare', 'cPanel', 'Uptime Kuma'],
      outputs: ['100% portal availability', 'Domain renewals', 'SSL certificates'],
      riskLevel: 'HIGH',
      department: 'IT Operations',
      evidence: ['Cloudflare audit logs', 'Weekly uptime records', 'DNS configuration commits'],
    },
    {
      responsibilityId: 'resp_wp_custom',
      title: 'WordPress Customization & Plugin Maintenance',
      description: 'Develops theme adjustments, updates core CMS and plugins, and fixes broken layouts on institutional portals.',
      frequency: 'WEEKLY',
      estimatedHoursPerWeek: 10,
      skills: ['WordPress', 'PHP', 'Plugin Debugging', 'Elementor'],
      tools: ['WordPress Admin', 'FTP/SFTP', 'LiteSpeed Cache'],
      outputs: ['Updated plugins', 'Patched theme components', 'Speed optimizations'],
      riskLevel: 'MEDIUM',
      department: 'Web Engineering',
      evidence: ['WordPress changelog records', 'Plugin test logs in staging'],
    },
    {
      responsibilityId: 'resp_graphic_design',
      title: 'Graphic Design, Marketing Visuals & Publication Collaterals',
      description: 'Designs banners, posters, social media cards, annual reports, and event branding assets.',
      frequency: 'DAILY',
      estimatedHoursPerWeek: 14,
      skills: ['Adobe Illustrator', 'Photoshop', 'Typography', 'Color Grading'],
      tools: ['Adobe Illustrator', 'Photoshop', 'Figma'],
      outputs: ['Event banners', 'Social media flyers', 'PDF report covers'],
      riskLevel: 'LOW',
      department: 'Creative & Media',
      evidence: ['Design archive folder', 'Approved print flyers', 'Exported vector artwork'],
    },
    {
      responsibilityId: 'resp_social_media',
      title: 'Social Media Distribution & Engagement Scheduling',
      description: 'Coordinates post scheduling, caption copy, and daily audience notifications across Instagram and Facebook.',
      frequency: 'DAILY',
      estimatedHoursPerWeek: 8,
      skills: ['Copywriting', 'Content Scheduling', 'Community Engagement'],
      tools: ['Meta Business Suite', 'Instagram'],
      outputs: ['Scheduled weekly feeds', 'Story announcements', 'Follower responses'],
      riskLevel: 'LOW',
      department: 'Marketing',
      evidence: ['Published post logs', 'Meta Business Suite scheduled queue'],
    },
    {
      responsibilityId: 'resp_content_publishing',
      title: 'Content Writing, Decree Formatting & Academic Publishing',
      description: 'Transcribes, formats, and publishes formal decrees (SK), student achievements, and academic news articles.',
      frequency: 'WEEKLY',
      estimatedHoursPerWeek: 8,
      skills: ['Editorial Writing', 'Decree Formatting', 'Proofreading'],
      tools: ['Google Docs', 'WordPress Editor'],
      outputs: ['Published official decrees', 'Campus news articles'],
      riskLevel: 'MEDIUM',
      department: 'Academic Administration',
      evidence: ['Published articles on campus portal', 'PDF decree attachments'],
    },
    {
      responsibilityId: 'resp_it_support',
      title: 'Internal IT Helpdesk & Hardware/Network Troubleshooting',
      description: 'Provides on-site hardware troubleshooting, printer maintenance, LAN cable crimping, and desktop support.',
      frequency: 'DAILY',
      estimatedHoursPerWeek: 8,
      skills: ['Hardware Repair', 'LAN Setup', 'Windows Troubleshooting', 'Printer Maintenance'],
      tools: ['Mikrotik Winbox', 'AnyDesk', 'Hardware Toolkit'],
      outputs: ['Fixed workstations', 'Operational office LAN', 'Configured network printers'],
      riskLevel: 'LOW',
      department: 'IT Support',
      evidence: ['IT support ticket log', 'Hardware maintenance receipts'],
    },
  ],
  mappings: [
    {
      mappingId: 'map_1',
      responsibilityId: 'resp_web_admin',
      marketRoleId: 'mkt_web_admin',
      marketRoleTitle: 'Web Administrator',
      matchConfidence: 'HIGH',
      matchReason: ['Direct alignment with DNS, server maintenance, and domain operations.'],
      reviewStatus: 'VERIFIED',
      allocationPercentage: 100, // 1.0 FTE
      overlapFactor: 0.0,
      reviewedBy: 'Ahmad (System Architect)',
      reviewedAt: '2026-09-30T00:00:00Z',
    },
    {
      mappingId: 'map_2',
      responsibilityId: 'resp_wp_custom',
      marketRoleId: 'mkt_wp_specialist',
      marketRoleTitle: 'WordPress / CMS Specialist',
      matchConfidence: 'HIGH',
      matchReason: ['Handles specialized theme customization and CMS plugin debugging.'],
      reviewStatus: 'VERIFIED',
      allocationPercentage: 40, // 0.4 FTE
      overlapFactor: 0.1, // Controlled for overlap with Web Admin
      reviewedBy: 'Ahmad (System Architect)',
      reviewedAt: '2026-09-30T00:00:00Z',
    },
    {
      mappingId: 'map_3',
      responsibilityId: 'resp_graphic_design',
      marketRoleId: 'mkt_graphic_designer',
      marketRoleTitle: 'Graphic Designer',
      matchConfidence: 'HIGH',
      matchReason: ['Full creative production of banners, vectors, and publication layouts.'],
      reviewStatus: 'VERIFIED',
      allocationPercentage: 60, // 0.6 FTE
      overlapFactor: 0.0,
      reviewedBy: 'Maya (Product Manager)',
      reviewedAt: '2026-09-30T00:00:00Z',
    },
    {
      mappingId: 'map_4',
      responsibilityId: 'resp_social_media',
      marketRoleId: 'mkt_social_media',
      marketRoleTitle: 'Social Media Specialist',
      matchConfidence: 'HIGH',
      matchReason: ['Execution of marketing distribution and channel community management.'],
      reviewStatus: 'VERIFIED',
      allocationPercentage: 40, // 0.4 FTE
      overlapFactor: 0.0,
      reviewedBy: 'Maya (Product Manager)',
      reviewedAt: '2026-09-30T00:00:00Z',
    },
    {
      mappingId: 'map_5',
      responsibilityId: 'resp_content_publishing',
      marketRoleId: 'mkt_content_spec',
      marketRoleTitle: 'Content Publishing Specialist',
      matchConfidence: 'MEDIUM',
      matchReason: ['Formal decree editorial formatting and academic web articles.'],
      reviewStatus: 'VERIFIED',
      allocationPercentage: 50, // 0.5 FTE
      overlapFactor: 0.0,
      reviewedBy: 'Ahmad (System Architect)',
      reviewedAt: '2026-09-30T00:00:00Z',
    },
    {
      mappingId: 'map_6',
      responsibilityId: 'resp_it_support',
      marketRoleId: 'mkt_it_support',
      marketRoleTitle: 'IT Support Specialist',
      matchConfidence: 'HIGH',
      matchReason: ['On-site desktop, hardware, and LAN network troubleshooting.'],
      reviewStatus: 'VERIFIED',
      allocationPercentage: 30, // 0.3 FTE
      overlapFactor: 0.0,
      reviewedBy: 'Ahmad (System Architect)',
      reviewedAt: '2026-09-30T00:00:00Z',
    },
  ],
  equivalentRoles: [
    {
      marketRoleId: 'mkt_web_admin',
      marketRoleTitle: 'Web Administrator',
      allocationPercentage: 100,
      equivalentFte: 1.0,
      benchmark: INITIAL_SALARY_BENCHMARKS[0], // 4.2M - 5.5M - 7.0M
      illustrativeValueMin: 4200000,
      illustrativeValueMedian: 5500000,
      illustrativeValueMax: 7000000,
    },
    {
      marketRoleId: 'mkt_wp_specialist',
      marketRoleTitle: 'WordPress / CMS Specialist',
      allocationPercentage: 40,
      equivalentFte: 0.4,
      benchmark: INITIAL_SALARY_BENCHMARKS[1], // 4.0M - 5.0M - 6.5M
      illustrativeValueMin: 1600000, // 4.0M * 0.4
      illustrativeValueMedian: 2000000, // 5.0M * 0.4
      illustrativeValueMax: 2600000, // 6.5M * 0.4
    },
    {
      marketRoleId: 'mkt_graphic_designer',
      marketRoleTitle: 'Graphic Designer',
      allocationPercentage: 60,
      equivalentFte: 0.6,
      benchmark: INITIAL_SALARY_BENCHMARKS[2], // 3.8M - 4.8M - 6.5M
      illustrativeValueMin: 2280000, // 3.8M * 0.6
      illustrativeValueMedian: 2880000, // 4.8M * 0.6
      illustrativeValueMax: 3900000, // 6.5M * 0.6
    },
    {
      marketRoleId: 'mkt_social_media',
      marketRoleTitle: 'Social Media Specialist',
      allocationPercentage: 40,
      equivalentFte: 0.4,
      benchmark: INITIAL_SALARY_BENCHMARKS[3], // 3.5M - 4.5M - 6.0M
      illustrativeValueMin: 1400000, // 3.5M * 0.4
      illustrativeValueMedian: 1800000, // 4.5M * 0.4
      illustrativeValueMax: 2400000, // 6.0M * 0.4
    },
    {
      marketRoleId: 'mkt_content_spec',
      marketRoleTitle: 'Content Publishing Specialist',
      allocationPercentage: 50,
      equivalentFte: 0.5,
      benchmark: INITIAL_SALARY_BENCHMARKS[4], // 3.5M - 4.2M - 5.5M
      illustrativeValueMin: 1750000, // 3.5M * 0.5
      illustrativeValueMedian: 2100000, // 4.2M * 0.5
      illustrativeValueMax: 2750000, // 5.5M * 0.5
    },
    {
      marketRoleId: 'mkt_it_support',
      marketRoleTitle: 'IT Support Specialist',
      allocationPercentage: 30,
      equivalentFte: 0.3,
      benchmark: INITIAL_SALARY_BENCHMARKS[5], // 4.0M - 5.0M - 6.8M
      illustrativeValueMin: 1200000, // 4.0M * 0.3
      illustrativeValueMedian: 1500000, // 5.0M * 0.3
      illustrativeValueMax: 2040000, // 6.8M * 0.3
    },
  ],
  totalEquivalentFte: 3.2, // 1.0 + 0.4 + 0.6 + 0.4 + 0.5 + 0.3 = 3.2 FTE
  illustrativeWorkforceValue: {
    monthlyMin: 12230000,
    monthlyMedian: 15580000, // 5.5M + 1.8M (with 10% overlap mitigation) + 2.88M + 1.8M + 2.1M + 1.5M
    monthlyMax: 20430000,
    annualizedMedian: 186960000, // 15.58M * 12
    currency: 'IDR',
  },
  illustrativeGap: {
    monthlyMin: 7730000, // 12.23M - 4.5M
    monthlyMedian: 11080000, // 15.58M - 4.5M
    monthlyMax: 15930000, // 20.43M - 4.5M
    annualizedMedian: 132960000, // 11.08M * 12
  },
  disclaimer: 'ILLUSTRATIVE MARKET WORKFORCE VALUATION ONLY. This analysis models the estimated market replacement cost for multiple equivalent job functions based on verified Central Java salary surveys. It does not constitute a legal salary entitlement or normative wage determination.',
  updatedAt: '2026-09-30T08:00:00Z',
};

/**
 * Canonical AI Virtual Employees with Virtual Compensation & Operating Costs
 */
export const INITIAL_VIRTUAL_EMPLOYEES: VirtualEmployee[] = [
  {
    agentId: 'AGT-ENG-001',
    name: 'Farhan',
    role: 'SOFTWARE_ENGINEER',
    internalRoleTitle: 'Lead Autonomous Software Engineer',
    department: 'Engineering',
    grade: 'GR-04',
    skills: ['TypeScript', 'React', 'NestJS', 'Laravel', 'PostgreSQL', 'Docker'],
    tools: ['Antigravity IDE', 'VS Code', 'Git', 'Terminal'],
    activeProjects: ['simmaci', 'koneksi-santri', 'kdi-ai-office'],
    virtualCompensation: {
      baseVirtualSalary: 12000000,
      allowance: 2000000,
      performanceIncentive: 1000000,
      totalMonthly: 15000000,
      currency: 'IDR',
    },
    operatingCost: {
      llmCostUsd: 150, // ~$2.4M IDR
      toolCostUsd: 40,
      infrastructureCostUsd: 50,
      totalMonthlyUsd: 240,
      totalMonthlyIdr: 3840000, // at 16,000 IDR/USD
    },
    totalCostMonthlyIdr: 18840000,
    tasksCompletedCount: 48,
    verifiedTasksCount: 48,
  },
  {
    agentId: 'AGT-ENG-002',
    name: 'Rian',
    role: 'FRONTEND_ENGINEER',
    internalRoleTitle: '3D WebGL & Frontend Engineer',
    department: 'Engineering',
    grade: 'GR-03',
    skills: ['PlayCanvas React', 'Three.js', 'Vite', 'TailwindCSS'],
    tools: ['PlayCanvas Editor', 'Vite Dev Server', 'Chrome DevTools'],
    activeProjects: ['kdi-ai-office', 'simmaci'],
    virtualCompensation: {
      baseVirtualSalary: 8500000,
      allowance: 1500000,
      performanceIncentive: 500000,
      totalMonthly: 10500000,
      currency: 'IDR',
    },
    operatingCost: {
      llmCostUsd: 95,
      toolCostUsd: 30,
      infrastructureCostUsd: 35,
      totalMonthlyUsd: 160,
      totalMonthlyIdr: 2560000,
    },
    totalCostMonthlyIdr: 13060000,
    tasksCompletedCount: 32,
    verifiedTasksCount: 32,
  },
  {
    agentId: 'AGT-ARCH-001',
    name: 'Ahmad',
    role: 'SYSTEM_ARCHITECT',
    internalRoleTitle: 'Principal Systems Architect',
    department: 'Architecture',
    grade: 'GR-06',
    skills: ['System Design', 'Neo4j Cypher', 'GraphRAG', 'Threat Modeling'],
    tools: ['Neo4j Browser', 'Docker', 'Ollama'],
    activeProjects: ['kdi-ai-office', 'graph-rag-memory', 'simmaci'],
    virtualCompensation: {
      baseVirtualSalary: 22000000,
      allowance: 3500000,
      performanceIncentive: 2000000,
      totalMonthly: 27500000,
      currency: 'IDR',
    },
    operatingCost: {
      llmCostUsd: 210,
      toolCostUsd: 50,
      infrastructureCostUsd: 80,
      totalMonthlyUsd: 340,
      totalMonthlyIdr: 5440000,
    },
    totalCostMonthlyIdr: 32940000,
    tasksCompletedCount: 26,
    verifiedTasksCount: 26,
  },
  {
    agentId: 'AGT-ENG-004',
    name: 'Nadia',
    role: 'QA_ENGINEER',
    internalRoleTitle: 'QA Automation & Security Engineer',
    department: 'Quality Assurance',
    grade: 'GR-04',
    skills: ['Automated Testing', 'AST Verification', 'OWASP Audit', 'Property Testing'],
    tools: ['Node Test Runner', 'OWASP ZAP', 'Postman'],
    activeProjects: ['simmaci', 'koneksi-santri', 'kdi-ai-office'],
    virtualCompensation: {
      baseVirtualSalary: 10500000,
      allowance: 1500000,
      performanceIncentive: 800000,
      totalMonthly: 12800000,
      currency: 'IDR',
    },
    operatingCost: {
      llmCostUsd: 120,
      toolCostUsd: 35,
      infrastructureCostUsd: 45,
      totalMonthlyUsd: 200,
      totalMonthlyIdr: 3200000,
    },
    totalCostMonthlyIdr: 16000000,
    tasksCompletedCount: 42,
    verifiedTasksCount: 42,
  },
  {
    agentId: 'AGT-PM-001',
    name: 'Maya',
    role: 'PRODUCT_MANAGER',
    internalRoleTitle: 'Product & Workload Delivery Manager',
    department: 'Product',
    grade: 'GR-05',
    skills: ['Task Decomposition', 'DAG Scheduling', 'Resource Allocation', 'Reporting'],
    tools: ['Linear', 'Notion', 'TaskQueue'],
    activeProjects: ['simmaci', 'koneksi-santri', 'kdi-ai-office'],
    virtualCompensation: {
      baseVirtualSalary: 14000000,
      allowance: 2000000,
      performanceIncentive: 1000000,
      totalMonthly: 17000000,
      currency: 'IDR',
    },
    operatingCost: {
      llmCostUsd: 110,
      toolCostUsd: 40,
      infrastructureCostUsd: 40,
      totalMonthlyUsd: 190,
      totalMonthlyIdr: 3040000,
    },
    totalCostMonthlyIdr: 20040000,
    tasksCompletedCount: 38,
    verifiedTasksCount: 38,
  },
];
